### PR TITLE
Wanted to use user data directory for persistency but got stuck..

### PR DESCRIPTION
**Pull request by paazmaya**
I need some input if this is the right approach to take, when I want to utilise persistent user data between sessions.

### CODE REVIEW

**Comment by aaltat** [comment]
By a quick look, idea looks good to go. @xylix or @mkorpela  do you see something, because your experience is better on node side.

**Comment by mkorpela** [comment]
Looks good. Tests fail

**Comment by aaltat** [comment]
Closing this due inactivity.

**Comment by paazmaya** [comment]
No worries, I will re-create when I have time to focus more.

**Pull request closed without merging**
