### PR TITLE
Topic/crawler

### PR DESCRIPTION
**Pull request by mkorpela**
Crawling a site for screenshots and errors.

### CODE REVIEW

**Comment by mkorpela** [comment]
- [ ] Make it BFS algo
- [ ] Control max deepness in branches
- [ ] Ignore some url pattern
- [ ] Check and report 404 and other errors
- [ ] Reuse already open page

**Comment by xylix** [comment]
Maybe the links dont have the correct href attribute set, but Crawl on my website https://xylix.fi/ fails by ignoring most links: 
```
==============================================================================
Tmp
==============================================================================
Tmp.Crawl
==============================================================================
Testing                                                               ...Crawling url https://xylix.fi/
Crawling url https://xylix.fi/things-of-interest/
Testing                                                               | PASS |
------------------------------------------------------------------------------
Tmp.Crawl                                                             | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Tmp                                                                   | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /Users/xylix/Code/robotframework-browser/output.xml
Log:     /Users/xylix/Code/robotframework-browser/log.html
Report:  /Users/xylix/Code/robotframework-browser/report.html
```

**Comment by mkorpela** [comment]
https://docs.scrapy.org/en/latest/intro/overview.html

**Comment by mkorpela** [comment]
https://stackoverflow.com/questions/5826581/is-the-a-href-property-always-returned-as-absolute

**Pull request merged**
