### PR TITLE
Fixes #370

### LINKED ISSUE #370: English proofreading required for CONTRIBUTING.md
English proofreading required for CONTRIBUTING.md.
Provide pull request to implement suggestions.

### PR DESCRIPTION
**Pull request by adrianyorke**
Corrections/suggestions after proofreading.

### CODE REVIEW

**Comment by adrianyorke** [comment]
I have removed the Code of Conduct text from this document and provided a link to the Code of Conduct document so the project has a single version of this text.

**Comment by adrianyorke** [comment]
@Snooz82 please review and merge this PR, thanks.

**Comment by Snooz82** [comment]
Done!

**Comment by mkorpela** [comment]
@all-contribuors please add adrianyork for documentation

**Pull request merged**
