### PR TITLE
Augment error messages helper

### PR DESCRIPTION
**Pull request by cmin764**
Fixes: [#1105](https://github.com/MarketSquare/robotframework-browser/issues/1105)
Enrich error messages with additional info based on the matched pattern and transformation function.

### ToDo
- [x] ~Unit tests~
- [x] Acceptance tests
- [x] Type annotations & linting

### CODE REVIEW

**Comment by cmin764** [comment]
Tested with [robot](https://github.com/cmin764/robots/blob/main/browser-auto/tasks.robot#L63-L67):
```robotframework
Test Timeout Message
    Browser.Open Browser    headless=${HEADLESS}
    Browser.Go To    https://google.com
    Set Browser Timeout    0.1s
    Click    nothing
```

and produces console output:
```
Test Timeout Message                                                  | FAIL |
TimeoutError: locator.click: Timeout 100ms exceeded.
=========================== logs ===========================
waiting for selector "nothing"
============================================================
Tip: Use "Set Browser Timeout" for setting a custom timeout.
```

**Comment by xylix** [comment]
Idea during sprint demos: Could also hint about the fact that keywords can also timeout not because they were too slow but for example if locator was not found in the page

**Comment by cmin764** [comment]
> Idea during sprint demos: Could also hint about the fact that keywords can also timeout not because they were too slow but for example if locator was not found in the page

Indeed, I refurbished the tip message now:
Screenshot 2022-05-18 at 19 32 38

**Comment by cmin764** [comment]
Tested it with `inv atest --suite "01_Browser_Management" -i timeout` and all tests are passing here.

**Review by xylix — APPROVED** [review]

**Comment by xylix** [comment]
Looks good to me if you're ready now 👍

**Pull request merged**
