### PR TITLE
Fix wait for regex and predicate handling

### PR DESCRIPTION
**Pull request by rsandbach**
- Standardized urlOrPredicate handling
 - Corrected grammar/spelling in waitForRequest log message.
 - Added acceptance tests for URL, RegEx, and Predicate.

### CODE REVIEW

**Comment by aaltat** [comment]
Please run `inv lint` locally and push changes back to the PR.

**Comment by rsandbach** [comment]
When I run `inv lint` , I get a message: `utest\test_waiters.py:13: error: Cannot assign to a method  [assignment]
Found 1 error in 1 file (checked 55 source files)` and it does not seem to run inv lint-robot. I ran it separately, and it modified all robot files. I committed only wait_for_http.robot.

**Comment by aaltat** [comment]
`inv lint-robot` fixes only the robot file. 

But it is interesting that you get that error, because it works in CI and it worked yesterday in my Mac.

**Comment by rsandbach** [comment]
> 

I did upgrade pip in my environment because there were some dependency issues with mypy. Let me recreate my venv and I'll see if that resolves the issue.

**Comment by rsandbach** [comment]
I am actually unable to build on Windows without updating pip.

A possible explination for why CI passes is that it looks like CI does not run `inv lint`, it runs the mypy command separately and it does not include the utest/ directory.

**tasks.py**
`c.run("mypy --show-error-codes --config-file Browser/mypy.ini Browser/ utest/")`

**CI**
image

**Comment by xylix** [comment]
I think running mypy for `utest` is something we need to fix on master. But I think the PR is working as expected now.

**Pull request merged**
