### PR TITLE
Take screenshot arguments

### PR DESCRIPTION
**Pull request by vincenzo-gasparo**
fileType is now an Enum with png and jpeg options, added new arguments definition to python doc #869

### CODE REVIEW

**Comment by vincenzo-gasparo** [comment]
@aaltat @mkorpela Can you check this please? I don't get the error, it's not related to my pr

**Comment by aaltat** [comment]
There are random failures now and then and this looks one of them. Rerunning.

**Comment by aaltat** [comment]
Test for the changed functionality would be good to have.

**Comment by aaltat** [comment]
Ah, this only enhances the previous impl.

**Review by mkorpela — APPROVED** [review]

**Comment by mkorpela** [comment]
Thanks for the contribution!

**Pull request merged**
